import { Shirt, Cpu, Car, Home as HomeIcon, Handshake, type LucideIcon } from 'lucide-react-native';
import { colors } from './theme';

export interface CategoryProduct {
  id: string;
  title: string;
  price: string;
  priceValue: number;
  location: string;
  seller: string;
  image: string;
  avatar: string;
  condition: 'Nuevo' | 'Como nuevo' | 'Buen estado' | 'Usado';
  subcategory: string;
}

export interface CategoryData {
  slug: string;
  label: string;
  Icon: LucideIcon;
  color: string;
  bg: string;
  hero: string;
  tagline: string;
  subcategories: string[];
  products: CategoryProduct[];
}

const sellerAvatars = [
  'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80',
  'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=80',
  'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=80',
  'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=80',
];

export const CATEGORIES: CategoryData[] = [
  {
    slug: 'moda',
    label: 'Moda',
    Icon: Shirt,
    color: colors.primary,
    bg: colors.primaryContainer + '1a',
    hero: 'https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg?auto=compress&cs=tinysrgb&w=1200',
    tagline: 'Ropa, calzado y accesorios para todos los estilos',
    subcategories: ['Todos', 'Ropa hombre', 'Ropa mujer', 'Calzado', 'Accesorios'],
    products: [
      {
        id: 'm1',
        title: 'Nike Air Zoom Pegasus 39',
        price: '85.000 XAF',
        priceValue: 85000,
        location: 'Malabo',
        seller: 'Jean-Pierre N.',
        image: 'https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Nuevo',
        subcategory: 'Calzado',
      },
      {
        id: 'm2',
        title: 'Chaqueta de cuero vintage',
        price: '45.000 XAF',
        priceValue: 45000,
        location: 'Bata',
        seller: 'Elena M.',
        image: 'https://images.pexels.com/photos/1124468/pexels-photo-1124468.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Como nuevo',
        subcategory: 'Ropa mujer',
      },
      {
        id: 'm3',
        title: 'Bolso elegante de cuero',
        price: '38.000 XAF',
        priceValue: 38000,
        location: 'Malabo',
        seller: 'Lucía B.',
        image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Nuevo',
        subcategory: 'Accesorios',
      },
      {
        id: 'm4',
        title: 'Reloj minimalista clásico',
        price: '52.000 XAF',
        priceValue: 52000,
        location: 'Malabo',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Buen estado',
        subcategory: 'Accesorios',
      },
      {
        id: 'm5',
        title: 'Camisa de algodón premium',
        price: '18.000 XAF',
        priceValue: 18000,
        location: 'Ebibeyin',
        seller: 'Carlos E.',
        image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Ropa hombre',
      },
      {
        id: 'm6',
        title: 'Vestido floral verano',
        price: '24.000 XAF',
        priceValue: 24000,
        location: 'Bata',
        seller: 'Estela N.',
        image: 'https://images.pexels.com/photos/972995/pexels-photo-972995.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[1],
        condition: 'Como nuevo',
        subcategory: 'Ropa mujer',
      },
    ],
  },
  {
    slug: 'tech',
    label: 'Tech',
    Icon: Cpu,
    color: colors.secondary,
    bg: colors.secondaryContainer + '1a',
    hero: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=1200',
    tagline: 'Smartphones, ordenadores y gadgets de última generación',
    subcategories: ['Todos', 'Móviles', 'Ordenadores', 'Audio', 'Cámaras', 'TV'],
    products: [
      {
        id: 't1',
        title: 'iPhone 15 Pro Max 256GB',
        price: '980.000 XAF',
        priceValue: 980000,
        location: 'Malabo',
        seller: 'Carlos E.',
        image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Móviles',
      },
      {
        id: 't2',
        title: 'MacBook Air M2 13"',
        price: '850.000 XAF',
        priceValue: 850000,
        location: 'Bata',
        seller: 'Estela N.',
        image: 'https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[1],
        condition: 'Como nuevo',
        subcategory: 'Ordenadores',
      },
      {
        id: 't3',
        title: 'Sony WH-1000XM5',
        price: '180.000 XAF',
        priceValue: 180000,
        location: 'Malabo',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Nuevo',
        subcategory: 'Audio',
      },
      {
        id: 't4',
        title: 'Cámara Sony Alpha 7 IV',
        price: '540.000 XAF',
        priceValue: 540000,
        location: 'Ebibeyin',
        seller: 'Lucía B.',
        image: 'https://images.pexels.com/photos/243757/pexels-photo-243757.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Como nuevo',
        subcategory: 'Cámaras',
      },
      {
        id: 't5',
        title: 'Smart TV Samsung 55" 4K',
        price: '320.000 XAF',
        priceValue: 320000,
        location: 'Malabo',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Nuevo',
        subcategory: 'TV',
      },
      {
        id: 't6',
        title: 'iPad Air 11" M3',
        price: '420.000 XAF',
        priceValue: 420000,
        location: 'Bata',
        seller: 'Jean-Pierre N.',
        image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Ordenadores',
      },
    ],
  },
  {
    slug: 'coches',
    label: 'Coches',
    Icon: Car,
    color: colors.tertiary,
    bg: colors.tertiaryContainer + '1a',
    hero: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1200',
    tagline: 'Vehículos de segunda mano y nuevos en Guinea Ecuatorial',
    subcategories: ['Todos', 'Sedán', 'SUV', 'Pickup', 'Motos'],
    products: [
      {
        id: 'c1',
        title: 'Toyota Corolla 2018',
        price: '8.500.000 XAF',
        priceValue: 8500000,
        location: 'Malabo',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Buen estado',
        subcategory: 'Sedán',
      },
      {
        id: 'c2',
        title: 'Toyota Hilux 4x4',
        price: '15.200.000 XAF',
        priceValue: 15200000,
        location: 'Bata',
        seller: 'Carlos E.',
        image: 'https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Como nuevo',
        subcategory: 'Pickup',
      },
      {
        id: 'c3',
        title: 'Honda CR-V 2020',
        price: '12.800.000 XAF',
        priceValue: 12800000,
        location: 'Malabo',
        seller: 'Estela N.',
        image: 'https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[1],
        condition: 'Como nuevo',
        subcategory: 'SUV',
      },
      {
        id: 'c4',
        title: 'Yamaha MT-07 2022',
        price: '4.200.000 XAF',
        priceValue: 4200000,
        location: 'Ebibeyin',
        seller: 'Jean-Pierre N.',
        image: 'https://images.pexels.com/photos/2393821/pexels-photo-2393821.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Motos',
      },
      {
        id: 'c5',
        title: 'Mercedes-Benz C-Class',
        price: '18.500.000 XAF',
        priceValue: 18500000,
        location: 'Malabo',
        seller: 'Lucía B.',
        image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Buen estado',
        subcategory: 'Sedán',
      },
      {
        id: 'c6',
        title: 'Nissan Patrol 2017',
        price: '11.000.000 XAF',
        priceValue: 11000000,
        location: 'Bata',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Buen estado',
        subcategory: 'SUV',
      },
    ],
  },
  {
    slug: 'hogar',
    label: 'Hogar',
    Icon: HomeIcon,
    color: colors.primary,
    bg: colors.primaryContainer + '1a',
    hero: 'https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg?auto=compress&cs=tinysrgb&w=1200',
    tagline: 'Muebles, decoración y electrodomésticos para tu hogar',
    subcategories: ['Todos', 'Muebles', 'Cocina', 'Decoración', 'Electrodomésticos'],
    products: [
      {
        id: 'h1',
        title: 'Sofá de 3 plazas moderno',
        price: '420.000 XAF',
        priceValue: 420000,
        location: 'Malabo',
        seller: 'Estela N.',
        image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[1],
        condition: 'Como nuevo',
        subcategory: 'Muebles',
      },
      {
        id: 'h2',
        title: 'Mesa de comedor de roble',
        price: '280.000 XAF',
        priceValue: 280000,
        location: 'Bata',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Buen estado',
        subcategory: 'Muebles',
      },
      {
        id: 'h3',
        title: 'Refrigerador LG 400L',
        price: '380.000 XAF',
        priceValue: 380000,
        location: 'Malabo',
        seller: 'Carlos E.',
        image: 'https://images.pexels.com/photos/2724748/pexels-photo-2724748.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Electrodomésticos',
      },
      {
        id: 'h4',
        title: 'Lámpara de pie minimalista',
        price: '45.000 XAF',
        priceValue: 45000,
        location: 'Malabo',
        seller: 'Lucía B.',
        image: 'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Nuevo',
        subcategory: 'Decoración',
      },
      {
        id: 'h5',
        title: 'Set de cocina premium 12 piezas',
        price: '95.000 XAF',
        priceValue: 95000,
        location: 'Ebibeyin',
        seller: 'Jean-Pierre N.',
        image: 'https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Cocina',
      },
      {
        id: 'h6',
        title: 'Alfombra persa decorativa',
        price: '120.000 XAF',
        priceValue: 120000,
        location: 'Bata',
        seller: 'Elena M.',
        image: 'https://images.pexels.com/photos/1571463/pexels-photo-1571463.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Como nuevo',
        subcategory: 'Decoración',
      },
    ],
  },
  {
    slug: 'servicios',
    label: 'Servicios',
    Icon: Handshake,
    color: colors.secondary,
    bg: colors.secondaryContainer + '1a',
    hero: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200',
    tagline: 'Profesionales y servicios de confianza cerca de ti',
    subcategories: ['Todos', 'Reformas', 'Clases', 'Belleza', 'Tecnología', 'Transporte'],
    products: [
      {
        id: 's1',
        title: 'Clases particulares de Inglés',
        price: '8.000 XAF/h',
        priceValue: 8000,
        location: 'Malabo',
        seller: 'Estela N.',
        image: 'https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[1],
        condition: 'Nuevo',
        subcategory: 'Clases',
      },
      {
        id: 's2',
        title: 'Reformas integrales del hogar',
        price: 'Desde 50.000 XAF',
        priceValue: 50000,
        location: 'Bata',
        seller: 'Antonio M.',
        image: 'https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[0],
        condition: 'Nuevo',
        subcategory: 'Reformas',
      },
      {
        id: 's3',
        title: 'Peluquería a domicilio',
        price: 'Desde 5.000 XAF',
        priceValue: 5000,
        location: 'Malabo',
        seller: 'Lucía B.',
        image: 'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Nuevo',
        subcategory: 'Belleza',
      },
      {
        id: 's4',
        title: 'Soporte técnico informático',
        price: 'Desde 10.000 XAF',
        priceValue: 10000,
        location: 'Malabo',
        seller: 'Carlos E.',
        image: 'https://images.pexels.com/photos/4974915/pexels-photo-4974915.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Tecnología',
      },
      {
        id: 's5',
        title: 'Mudanzas y transporte',
        price: 'Desde 25.000 XAF',
        priceValue: 25000,
        location: 'Ebibeyin',
        seller: 'Jean-Pierre N.',
        image: 'https://images.pexels.com/photos/4391470/pexels-photo-4391470.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[2],
        condition: 'Nuevo',
        subcategory: 'Transporte',
      },
      {
        id: 's6',
        title: 'Fotografía profesional eventos',
        price: 'Desde 75.000 XAF',
        priceValue: 75000,
        location: 'Bata',
        seller: 'Elena M.',
        image: 'https://images.pexels.com/photos/606541/pexels-photo-606541.jpeg?auto=compress&cs=tinysrgb&w=600',
        avatar: sellerAvatars[3],
        condition: 'Nuevo',
        subcategory: 'Tecnología',
      },
    ],
  },
];

/**
 * Related search terms per subcategory, used to power search suggestions
 * when navigating from the categories modal into Explore.
 */
export const SUBCATEGORY_SUGGESTIONS: Record<string, string[]> = {
  // Moda
  'Ropa hombre': ['Camisas', 'Pantalones', 'Chaquetas', 'Camisetas', 'Trajes'],
  'Ropa mujer': ['Vestidos', 'Blusas', 'Faldas', 'Abrigos', 'Tops'],
  Calzado: ['Zapatillas', 'Botas', 'Sandalias', 'Tacones', 'Nike'],
  Accesorios: ['Relojes', 'Bolsos', 'Gafas de sol', 'Cinturones', 'Joyas'],
  // Tech
  Móviles: ['iPhone', 'Samsung Galaxy', 'Xiaomi', 'Fundas', 'Cargadores'],
  Ordenadores: ['MacBook', 'Portátiles', 'PC Gaming', 'Monitores', 'Teclados'],
  Audio: ['Auriculares', 'Altavoces', 'AirPods', 'Cascos', 'Barras de sonido'],
  Cámaras: ['Canon', 'Sony Alpha', 'GoPro', 'Objetivos', 'Drones'],
  TV: ['Smart TV', 'TV 4K', 'Proyectores', 'Soportes TV', 'Chromecast'],
  // Coches
  Sedán: ['Toyota Corolla', 'Honda Civic', 'Mercedes', 'BMW Serie 3', 'Audi A4'],
  SUV: ['Toyota RAV4', 'Hyundai Tucson', 'Kia Sportage', 'Nissan X-Trail', 'Mazda CX-5'],
  Pickup: ['Toyota Hilux', 'Ford Ranger', 'Nissan Navara', 'Isuzu D-Max', 'Mitsubishi L200'],
  Motos: ['Yamaha', 'Honda', 'Scooter', 'Motos eléctricas', 'Cascos'],
  // Hogar
  Muebles: ['Sofás', 'Mesas', 'Sillas', 'Armarios', 'Camas'],
  Cocina: ['Ollas', 'Vajilla', 'Cafeteras', 'Cuchillos', 'Microondas'],
  Decoración: ['Lámparas', 'Cuadros', 'Espejos', 'Alfombras', 'Plantas'],
  Electrodomésticos: ['Nevera', 'Lavadora', 'Aire acondicionado', 'Ventiladores', 'Aspiradoras'],
  // Servicios
  Reformas: ['Fontanería', 'Electricista', 'Pintura', 'Albañilería', 'Carpintería'],
  Clases: ['Inglés', 'Matemáticas', 'Música', 'Informática', 'Conducir'],
  Belleza: ['Peluquería', 'Manicura', 'Maquillaje', 'Masajes', 'Estética'],
  Tecnología: ['Reparación móviles', 'Soporte PC', 'Diseño web', 'Redes', 'Instalaciones'],
  Transporte: ['Mudanzas', 'Taxi', 'Mensajería', 'Alquiler furgoneta', 'Portes'],
};
